version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - './nginx.vhost.conf:/etc/nginx/conf.d/default.conf'
      - '.:/usr/share/nginx/html'
      - './backend:/var/www/html/backend/'
      - './frontend:/var/www/html/frontend/'
    ports:
      - "${HOST_PORT:-8080}:80"
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
    environment:
      NODE_OPTIONS: "--max-old-space-size=${NODE_MEM_LIMIT:-4096}"
    working_dir: /app
    command: npm run dev
    ports:
      - "3727:3000"
      - "24678:24678"
  backend:
    build: ./backend
    volumes:
      - './backend:/app'
    working_dir: /app
    environment:
      OAUTH_REDIRECT_URI: "http://localhost:8080/oauth2/finalize_authorization"
      NODE_ENV: development
      JWT_SECRET: 873ee5be8195151ab434367c6061947e7ab66d0dfe7e961380d65377703d0ec8a6a7e2
      JWT_EXPIRE: 3600
      DEBUG: "bicode-api:*"
      RESPONSE_DELAY: "${RESPONSE_DELAY:-0}"
      FILE_UPLOADS_PATH: "/tmp"
    command: npm run dev
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
